
  ALTER TABLE "SDT_OWNER"."BULK_SUBMISSIONS" ADD CONSTRAINT "BS_SBR_UNI" UNIQUE ("SDT_BULK_REFERENCE") ENABLE;



  ALTER TABLE "SDT_OWNER"."SERVICE_TYPES" ADD CONSTRAINT "RT_RTN_UNI" UNIQUE ("SERVICE_TYPE_NAME") ENABLE;



  ALTER TABLE "SDT_OWNER"."TARGET_APPLICATIONS" ADD CONSTRAINT "TA_TAN_UNI" UNIQUE ("TARGET_APPLICATION_NAME") ENABLE;


