package uk.gov.moj.sdt.ws._2013.sdt.targetappinternalendpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-10-16T14:51:31.768+01:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.sdt.moj.gov.uk/2013/sdt/TargetAppInternalEndpoint", name = "ITargetAppInternalEndpointPortType")
@XmlSeeAlso({uk.gov.moj.sdt.ws._2013.sdt.baseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.sdt.targetapp.indvresponseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.sdt.targetapp.indvrequestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.sdt.targetapp.submitqueryrequestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.sdt.targetapp.submitqueryresponseschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ITargetAppInternalEndpointPortType {

    @WebResult(name = "submitQueryResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/sdt/targetApp/SubmitQueryResponseSchema", partName = "parameters")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.sdt.targetapp.submitqueryresponseschema.SubmitQueryResponseType submitQuery(
        @WebParam(partName = "parameters", name = "submitQueryRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/sdt/targetApp/SubmitQueryRequestSchema")
        uk.gov.moj.sdt.ws._2013.sdt.targetapp.submitqueryrequestschema.SubmitQueryRequestType parameters
    );

    @WebResult(name = "individualResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/sdt/targetApp/IndvResponseSchema", partName = "individualResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.sdt.targetapp.indvresponseschema.IndividualResponseType submitIndividual(
        @WebParam(partName = "individualRequest", name = "individualRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/sdt/targetApp/IndvRequestSchema")
        uk.gov.moj.sdt.ws._2013.sdt.targetapp.indvrequestschema.IndividualRequestType individualRequest
    );
}
