------------------------------------------------
-- Create each of the schemas used by SDT
------------------------------------------------

SET ECHO ON

CREATE USER SDT_OWNER IDENTIFIED BY SDT_OWNER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO SDT_OWNER;
ALTER USER SDT_OWNER QUOTA UNLIMITED ON USERS;

-- Additional users without schemas

CREATE USER SDT_USER IDENTIFIED BY SDT_USER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO SDT_USER;

CREATE USER SDT_BATCH_USER IDENTIFIED BY SDT_BATCH_USER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO SDT_BATCH_USER;

