------------------------------------------------
-- Create each of the schemas used by SDT
------------------------------------------------

SET ECHO ON

CREATE USER PUBLIC IDENTIFIED BY PUBLIC DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO PUBLIC;
GRANT INHERIT PRIVILEGES ON USER SYSTEM TO PUBLIC;
ALTER USER PUBLIC QUOTA UNLIMITED ON USERS;

-- Additional users without schemas

CREATE USER SDT_USER IDENTIFIED BY SDT_USER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO SDT_USER;

CREATE USER SDT_BATCH_USER IDENTIFIED BY SDT_BATCH_USER DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT,RESOURCE TO SDT_BATCH_USER;

