version: '2.1'

services:
  civil-sdt:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/civil-sdt
    environment:
      # these environment variables are used by java-logging library
      - CIVIL_SDT_S2S_KEY=AAAAAAAAAAAAAAAA
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - SDT_DB_HOST=civil-sdt-database
      - SDT_DB_USERNAME=std_user
      - SDT_DB_PASSWORD=std_pass
      # Uncomment following line and 5005 port mapping line below to enable remote JVM debugging
      #- JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    ports:
      - $SERVER_PORT:$SERVER_PORT
      # Uncomment following line and JAVA_TOOL_OPTIONS line above to enable remote JVM debugging
      #- 5005:5005
    depends_on:
      - civil-sdt-database
    links:
      - civil-sdt-database

  civil-sdt-database:
    build:
      context: docker/database
    image: hmcts/civil-sdt-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - SDT_DB_USERNAME=std_user
      - SDT_DB_PASSWORD=std_pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5455:5432
    volumes:
      - civil-sdt-database-data:/var/lib/postgresql/data

volumes:
  civil-sdt-database-data:

