spring:
  jms:
    servicebus:
      enabled: false
    activemq:
      in-memory: true
      pool:
        enabled: false
      internal:
        queueConfig:
          MCOL: ${MCOL.Queue}
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:tc:postgresql:11:///civil_sdt_integ?stringtype=unspecified
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: ${SDT_DB_USERNAME:postgres}
    password: ${SDT_DB_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  flyway:
    enabled: false
