-----------------
--- Object Grants
-----------------

  GRANT DELETE ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "SDT_OWNER"."GLOBAL_PARAMETERS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT EXECUTE ON "SDT_OWNER"."PURGE" TO "SDT_BATCH_USER";


  GRANT DELETE ON "SDT_OWNER"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT DELETE ON "SDT_OWNER"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT INSERT ON "SDT_OWNER"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "SDT_OWNER"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_CUST_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_CUST_APP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."BULK_SUB_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."ERR_LOG_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."ERR_MESG_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."GLB_PAR_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."IND_REQ_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SER_ROU_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SER_TYP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."TAR_APP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SDT_REF_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "SDT_OWNER"."SRV_REQ_SEQ" TO "SDT_USER";

-----------------
--- System Grants
-----------------

  GRANT UNLIMITED TABLESPACE TO "SDT_OWNER";


  GRANT CREATE SYNONYM TO "SDT_USER";


  GRANT CREATE SYNONYM TO "SDT_BATCH_USER";

-----------------
--- Sys Grants
-----------------

  GRANT EXECUTE ON "SYS"."UTL_FILE" TO "SDT_OWNER";