/* Copyrights and Licenses
 * 
 * Copyright (c) 2012-2013 by the Ministry of Justice. All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 * - All advertising materials mentioning features or use of this software must display the
 * following acknowledgment: "This product includes Money Claims OnLine."
 * - Products derived from this software may not be called "Money Claims OnLine" nor may
 * "Money Claims OnLine" appear in their names without prior written permission of the
 * Ministry of Justice.
 * - Redistributions of any form whatsoever must retain the following acknowledgment: "This
 * product includes Money Claims OnLine."
 * This software is provided "as is" and any expressed or implied warranties, including, but
 * not limited to, the implied warranties of merchantability and fitness for a particular purpose are
 * disclaimed. In no event shall the Ministry of Justice or its contributors be liable for any
 * direct, indirect, incidental, special, exemplary, or consequential damages (including, but
 * not limited to, procurement of substitute goods or services; loss of use, data, or profits;
 * or business interruption). However caused any on any theory of liability, whether in contract,
 * strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this
 * software, even if advised of the possibility of such damage.
 * 
 * $Id: $
 * $LastChangedRevision: $
 * $LastChangedDate: $
 * $LastChangedBy: $ */


package uk.gov.moj.sdt.domain;

import java.util.List;

import org.joda.time.LocalDateTime;

/**
 * For a Submit Bulk Request, the SDT application records the 
 * Bulk Submissions detail when processing a Bulk Request.
 * 
 * @author d130680
 *
 */
public class BulkSubmission {	
	
	/**
	 * Primary key.
	 */
	private int id;
	
	/**
	 * Bulk customer.
	 */
	private BulkCustomer bulkCustomer;
	
	/**
	 * The target application that SDT routes the Bulk Request onto for subsequent processing.
	 */
	private TargetApplication targetApplication;
	
	/**
	 * A unique SDT Reference (unique within the SDT Data Retention Period) 
	 * generated by SDT and assigned to a single Bulk Request.
	 */
	private String sdtBulkReference;
	
	/**
	 * A unique End User specified Reference (unique within the SDT Data Retention Period) 
	 * assigned to a single Bulk Request. 
	 */
	private String customerReference;
	
	/**
	 * Date record was created.
	 */
	private LocalDateTime createdDate;
	
	/**
	 * The total number of requests expected to be contained within the Bulk Request. 
	 */
	private int numberOfRequest;
	
	/**
	 * The status of the Bulk Request - one of "Uploaded", "Failed", "Validated", or "Completed" 
	 * to reflect the current status of SDT processing. Maintained by SDT.
	 */
	private String submissionStatus;
	
	/**
	 * Date/Time the Bulk Request completed processing.
	 */
	private LocalDateTime completedDate;
	
	/**
	 * Date record was updated.
	 */
	private LocalDateTime updatedDate;
	
	/**
	 * Hibernate version number.
	 */
	private int version;
	
	/**
	 * XML payload.
	 */
	private String payload;
	
	/**
	 * List of individual requests.
	 */
	private List<IndividualRequest> individualRequests;


	/**
	 * Get primary key.
	 * @return primary key
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * Set primary key.
	 * 
	 * @param id primary key
	 */
	public void setId(final int id) {
		this.id = id;
	}

	/**
	 * Get the Bulk Customer.
	 * @return bulk customer
	 */
	public BulkCustomer getBulkCustomer() {
		return bulkCustomer;
	}

	/**
	 * Set the Bulk Customer.
	 * @param bulkCustomer bulk customer
	 */
	public void setBulkCustomer(final BulkCustomer bulkCustomer) {
		this.bulkCustomer = bulkCustomer;
	}
	
	/**
	 * Get the Target Application.
	 * @return target application
	 */
	public TargetApplication getTargetApplication() {
		return targetApplication;
	}

	/**
	 * Set the Target Application.
	 * @param targetApplication target application
	 */
	public void setTargetApplication(final TargetApplication targetApplication) {
		this.targetApplication = targetApplication;
	}

	/**
	 * Get SDT bulk reference.
	 * @return SDT bulk reference
	 */
	public String getSdtBulkReference() {
		return sdtBulkReference;
	}

	/**
	 * Set SDT bulk reference.
	 * @param sdtBulkReference SDT bulk reference
	 */
	public void setSdtBulkReference(final String sdtBulkReference) {
		this.sdtBulkReference = sdtBulkReference;
	}

	/**
	 * Get customer reference.
	 * @return customer reference
	 */
	public String getCustomerReference() {
		return customerReference;
	}

	/**
	 * Set customer reference.
	 * @param customerReference customer reference
	 */
	public void setCustomerReference(final String customerReference) {
		this.customerReference = customerReference;
	}

	/**
	 * Get created date.
	 * @return created date
	 */
	public LocalDateTime getCreatedDate() {
		return createdDate;
	}

	/**
	 * Set created date.
	 * @param createdDate created dated
	 */
	public void setCreatedDate(final LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Get number of request.
	 * @return number of request
	 */
	public int getNumberOfRequest() {
		return numberOfRequest;
	}

	/**
	 * Set number of request.
	 * @param numberOfRequest number of request
	 */
	public void setNumberOfRequest(final int numberOfRequest) {
		this.numberOfRequest = numberOfRequest;
	}

	/**
	 * Get submission status.
	 * @return submission status
	 */
	public String getSubmissionStatus() {
		return submissionStatus;
	}

	/**
	 * Set submission status.
	 * @param submissionStatus submission status
	 */
	public void setSubmissionStatus(final String submissionStatus) {
		this.submissionStatus = submissionStatus;
	}

	/**
	 * Get completed date.
	 * @return completed date
	 */
	public LocalDateTime getCompletedDate() {
		return completedDate;
	}

	/**
	 * Set completed date.
	 * @param completedDate completed date
	 */
	public void setCompletedDate(final LocalDateTime completedDate) {
		this.completedDate = completedDate;
	}

	/**
	 * Get updated date.
	 * @return updated date
	 */
	public LocalDateTime getUpdatedDate() {
		return updatedDate;
	}

	/**
	 * Set updated date.
	 * @param updatedDate updated date
	 */
	public void setUpdatedDate(final LocalDateTime updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * Get the XML payload.
	 * @return xml payload
	 */
	public String getPayload() {
		return payload;
	}

	/**
	 * Set the XML payload.
	 * @param payload xml payload
	 */
	public void setPayload(final String payload) {
		this.payload = payload;
	}

	/**
	 * Get Hibernate version id.
	 * @return Hibernate version id
	 */
	public int getVersion() {
		return version;
	}

	/**
	 * Get list of individual request.
	 * 
	 * @return list of individual requests
	 */
	public List<IndividualRequest> getIndividualRequests() {
		return individualRequests;
	}

	/**
	 * Set list of individual request.
	 * 
	 * @param individualRequests list of individual request
	 */
	public void setIndividualRequests(final List<IndividualRequest> individualRequests) {
		this.individualRequests = individualRequests;
	}
	
	
}
