TRUNCATE TABLE INDIVIDUAL_REQUESTS CASCADE;

INSERT INTO INDIVIDUAL_REQUESTS (INDIVIDUAL_REQUEST_ID, BULK_SUBMISSION_ID, CUSTOMER_REQUEST_REF, REQUEST_STATUS, SDT_BULK_REFERENCE, LINE_NUMBER, SDT_REQUEST_REFERENCE, CREATED_DATE, UPDATED_DATE, FORWARDING_ATTEMPTS,
      TARGET_APPLICATION_RESPONSE, REQUEST_TYPE, VERSION_NUMBER, DEAD_LETTER)
VALUES (1, 14, 'USER_REQUEST_ID_BF1', 'Accepted', 'MCOL-10012013010101-100099999', 1, 'MCOL-10012013010101-100099999-0002000', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 1 ,
      '<ind:mcolResponseDetail xmlns:ind="http://ws.sdt.moj.gov.uk/2013/sdt/BulkFeedbackResponseSchema" xmlns:mresp="http://ws.sdt.moj.gov.uk/2013/mcol/ResponseDetailSchema"><mresp:claimNumber>21346546</mresp:claimNumber><mresp:issueDate>2001-01-01</mresp:issueDate><mresp:serviceDate>2001-01-01</mresp:serviceDate><mresp:warrantNumber>12345678</mresp:warrantNumber><mresp:enforcingCourtCode>123</mresp:enforcingCourtCode><mresp:enforcingCourtName>Court Code</mresp:enforcingCourtName><mresp:fee>0</mresp:fee><mresp:judgmentWarrantStatus>tns:additionalStatus</mresp:judgmentWarrantStatus></ind:mcolResponseDetail>', 'mcolClaim', 0, false);

INSERT INTO INDIVIDUAL_REQUESTS (INDIVIDUAL_REQUEST_ID, BULK_SUBMISSION_ID, CUSTOMER_REQUEST_REF, REQUEST_STATUS, SDT_BULK_REFERENCE, LINE_NUMBER, SDT_REQUEST_REFERENCE, CREATED_DATE, UPDATED_DATE, FORWARDING_ATTEMPTS,
      TARGET_APPLICATION_RESPONSE, REQUEST_TYPE, VERSION_NUMBER, DEAD_LETTER)
VALUES (2, 14, 'USER_REQUEST_ID_BF2', 'Accepted', 'MCOL-10012013010101-100099999', 2, 'MCOL-10012013010101-100099999-0002000', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 1 ,
      '<ind:mcolResponseDetail xmlns:ind="http://ws.sdt.moj.gov.uk/2013/sdt/BulkFeedbackResponseSchema" xmlns:mresp="http://ws.sdt.moj.gov.uk/2013/mcol/ResponseDetailSchema"><mresp:claimNumber>21346546</mresp:claimNumber><mresp:issueDate>2001-01-01</mresp:issueDate><mresp:serviceDate>2001-01-01</mresp:serviceDate><mresp:warrantNumber>12345678</mresp:warrantNumber><mresp:enforcingCourtCode>123</mresp:enforcingCourtCode><mresp:enforcingCourtName>Court Code</mresp:enforcingCourtName><mresp:fee>0</mresp:fee><mresp:judgmentWarrantStatus>tns:additionalStatus</mresp:judgmentWarrantStatus></ind:mcolResponseDetail>', 'mcolClaim', 0, false);

INSERT INTO INDIVIDUAL_REQUESTS (INDIVIDUAL_REQUEST_ID, BULK_SUBMISSION_ID, CUSTOMER_REQUEST_REF, REQUEST_STATUS, SDT_BULK_REFERENCE, LINE_NUMBER, SDT_REQUEST_REFERENCE, CREATED_DATE, UPDATED_DATE, FORWARDING_ATTEMPTS,
      TARGET_APPLICATION_RESPONSE, REQUEST_TYPE, VERSION_NUMBER, DEAD_LETTER)
VALUES (3, 14, 'USER_REQUEST_ID_BF3', 'Accepted', 'MCOL-10012013010101-100099999', 3, 'MCOL-10012013010101-100099999-0002000', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 1 ,
      '<ind:mcolResponseDetail xmlns:ind="http://ws.sdt.moj.gov.uk/2013/sdt/BulkFeedbackResponseSchema" xmlns:mresp="http://ws.sdt.moj.gov.uk/2013/mcol/ResponseDetailSchema"><mresp:claimNumber>21346546</mresp:claimNumber><mresp:issueDate>2001-01-01</mresp:issueDate><mresp:serviceDate>2001-01-01</mresp:serviceDate><mresp:warrantNumber>12345678</mresp:warrantNumber><mresp:enforcingCourtCode>123</mresp:enforcingCourtCode><mresp:enforcingCourtName>Court Code</mresp:enforcingCourtName><mresp:fee>0</mresp:fee><mresp:judgmentWarrantStatus>tns:additionalStatus</mresp:judgmentWarrantStatus></ind:mcolResponseDetail>', 'mcolClaim', 0, false);
