TRUNCATE TABLE BULK_SUBMISSIONS CASCADE;

INSERT INTO BULK_SUBMISSIONS (BULK_SUBMISSION_ID, BULK_CUSTOMER_ID, TARGET_APPLICATION_ID, SDT_BULK_REFERENCE, CUSTOMER_REFERENCE, CREATED_DATE, NUMBER_OF_REQUESTS, BULK_SUBMISSION_STATUS, VERSION_NUMBER, BULK_PAYLOAD)
VALUES(14, 10711, 10713, 'MCOL-10012013010101-100099999', 'REF1', (current_date - INTERVAL '1 day'), 1, 'Uploaded', 0, 'MTIzNDU=');
