insert into BULK_CUSTOMERS (BULK_CUSTOMER_ID, SDT_CUSTOMER_ID, VERSION_NUMBER) values (10711, 2, 0);

insert into SERVICE_REQUESTS (SERVICE_REQUEST_ID, REQUEST_PAYLOAD, REQUEST_TIMESTAMP, RESPONSE_PAYLOAD, RESPONSE_TIMESTAMP,
                              REQUEST_TYPE, SDT_CUSTOMER_ID, SDT_BULK_REFERENCE, VERSION_NUMBER)
values (10800, 'MTIzNDU=', now(), 'MTIzNDU=', now(), 'mcolClaim', 2, '12345678', 0);


insert into BULK_CUSTOMER_APPLICATIONS (BULK_CUSTOMER_APPLICATIONS_ID, BULK_CUSTOMER_ID, TARGET_APPLICATION_ID, CUSTOMER_APPLICATION_ID, VERSION_NUMBER)
values (1, 10711, 1, 1, 0);

