-----------------
--- Object Grants
-----------------

  GRANT DELETE ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "PUBLIC"."ERROR_LOGS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "PUBLIC"."ERROR_LOGS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "PUBLIC"."GLOBAL_PARAMETERS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT DELETE ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT SELECT ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_BATCH_USER";
 
  GRANT EXECUTE ON "PUBLIC"."PURGE" TO "SDT_BATCH_USER";


  GRANT DELETE ON "PUBLIC"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."BULK_CUSTOMERS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."BULK_SUBMISSIONS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."ERROR_LOGS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."ERROR_MESSAGES" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."GLOBAL_PARAMETERS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."INDIVIDUAL_REQUESTS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."SERVICE_ROUTINGS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."SERVICE_TYPES" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."SERVICE_REQUESTS" TO "SDT_USER";
 
  GRANT DELETE ON "PUBLIC"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT INSERT ON "PUBLIC"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT UPDATE ON "PUBLIC"."TARGET_APPLICATIONS" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_CUST_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_CUST_APP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."BULK_SUB_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."ERR_LOG_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."ERR_MESG_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."GLB_PAR_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."IND_REQ_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SER_ROU_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SER_TYP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."TAR_APP_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SDT_REF_SEQ" TO "SDT_USER";
 
  GRANT SELECT ON "PUBLIC"."SRV_REQ_SEQ" TO "SDT_USER";

-----------------
--- System Grants
-----------------

  GRANT UNLIMITED TABLESPACE TO "PUBLIC";


  GRANT CREATE SYNONYM TO "SDT_USER";


  GRANT CREATE SYNONYM TO "SDT_BATCH_USER";

-----------------
--- Sys Grants
-----------------

  GRANT EXECUTE ON "SYS"."UTL_FILE" TO "PUBLIC";
