ALTER TABLE "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" ADD CONSTRAINT "BCA_BULK_CUSTOMER_FK" FOREIGN KEY ("BULK_CUSTOMER_ID")
	  REFERENCES "PUBLIC"."BULK_CUSTOMERS" ("BULK_CUSTOMER_ID") ENABLE;

ALTER TABLE "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" ADD CONSTRAINT "BCA_TARGET_APPLICATION_FK" FOREIGN KEY ("TARGET_APPLICATION_ID")
	  REFERENCES "PUBLIC"."TARGET_APPLICATIONS" ("TARGET_APPLICATION_ID") ENABLE;

ALTER TABLE "PUBLIC"."BULK_SUBMISSIONS" ADD CONSTRAINT "BS_CUSTOMER_ID_FK" FOREIGN KEY ("BULK_CUSTOMER_ID")
	  REFERENCES "PUBLIC"."BULK_CUSTOMERS" ("BULK_CUSTOMER_ID") ENABLE;

ALTER TABLE "PUBLIC"."BULK_SUBMISSIONS" ADD CONSTRAINT "BS_SERVICE_REQUEST_ID_FK" FOREIGN KEY ("SERVICE_REQUEST_ID")
	  REFERENCES "PUBLIC"."SERVICE_REQUESTS" ("SERVICE_REQUEST_ID") ENABLE;

ALTER TABLE "PUBLIC"."BULK_SUBMISSIONS" ADD CONSTRAINT "BS_TARGET_APPLICATION_FK" FOREIGN KEY ("TARGET_APPLICATION_ID")
	  REFERENCES "PUBLIC"."TARGET_APPLICATIONS" ("TARGET_APPLICATION_ID") ENABLE;

ALTER TABLE "PUBLIC"."ERROR_LOGS" ADD CONSTRAINT "EL_INDIVIDUAL_REQUEST_FK" FOREIGN KEY ("INDIVIDUAL_REQUEST_ID")
	  REFERENCES "PUBLIC"."INDIVIDUAL_REQUESTS" ("INDIVIDUAL_REQUEST_ID") ENABLE;

ALTER TABLE "PUBLIC"."INDIVIDUAL_REQUESTS" ADD CONSTRAINT "IR_BULK_SUBMISSION_FK" FOREIGN KEY ("BULK_SUBMISSION_ID")
	  REFERENCES "PUBLIC"."BULK_SUBMISSIONS" ("BULK_SUBMISSION_ID") ENABLE;

ALTER TABLE "PUBLIC"."SERVICE_ROUTINGS" ADD CONSTRAINT "SR_SERVICE_TYPE_FK" FOREIGN KEY ("SERVICE_TYPE_ID")
	  REFERENCES "PUBLIC"."SERVICE_TYPES" ("SERVICE_TYPE_ID") ENABLE;

ALTER TABLE "PUBLIC"."SERVICE_ROUTINGS" ADD CONSTRAINT "SR_TARGET_APPLICATION_FK" FOREIGN KEY ("TARGET_APPLICATION_ID")
	  REFERENCES "PUBLIC"."TARGET_APPLICATIONS" ("TARGET_APPLICATION_ID") ENABLE;
