
  ALTER TABLE "PUBLIC"."BULK_CUSTOMERS" ADD CONSTRAINT "BULK_CUSTOMERS_PK" PRIMARY KEY ("BULK_CUSTOMER_ID") using index PUBLIC.BULK_CUSTOMERS_PK ENABLE;



  ALTER TABLE "PUBLIC"."BULK_CUSTOMER_APPLICATIONS" ADD CONSTRAINT "BULK_CUSTOMER_APPLICATIONS_PK" PRIMARY KEY ("BULK_CUSTOMER_APPLICATIONS_ID") using index PUBLIC.BULK_CUSTOMER_APPLICATIONS_PK ENABLE;



  ALTER TABLE "PUBLIC"."BULK_SUBMISSIONS" ADD CONSTRAINT "BULK_SUBMISSIONS_PK" PRIMARY KEY ("BULK_SUBMISSION_ID") using index PUBLIC.BULK_SUBMISSIONS_PK ENABLE;



  ALTER TABLE "PUBLIC"."ERROR_LOGS" ADD CONSTRAINT "ERROR_LOGS_PK" PRIMARY KEY ("ERROR_LOG_ID") using index PUBLIC.ERROR_LOGS_PK ENABLE;



  ALTER TABLE "PUBLIC"."ERROR_MESSAGES" ADD CONSTRAINT "ERROR_MESSAGES_PK" PRIMARY KEY ("ERROR_MESSAGE_ID") using index PUBLIC.ERROR_MESSAGES_PK ENABLE;



  ALTER TABLE "PUBLIC"."GLOBAL_PARAMETERS" ADD CONSTRAINT "GLOBAL_PARAMETERS_PK" PRIMARY KEY ("GLOBAL_PARAMETER_ID") using index PUBLIC.GLOBAL_PARAMETERS_PK ENABLE;



  ALTER TABLE "PUBLIC"."INDIVIDUAL_REQUESTS" ADD CONSTRAINT "INDIVIDUAL_REQUESTS_PK" PRIMARY KEY ("INDIVIDUAL_REQUEST_ID") using index PUBLIC.INDIVIDUAL_REQUESTS_PK ENABLE;



  ALTER TABLE "PUBLIC"."SERVICE_REQUESTS" ADD CONSTRAINT "SERVICE_REQUESTS_PK" PRIMARY KEY ("SERVICE_REQUEST_ID") using index PUBLIC.SERVICE_REQUESTS_PK ENABLE;



  ALTER TABLE "PUBLIC"."SERVICE_ROUTINGS" ADD CONSTRAINT "SERVICE_ROUTINGS_PK" PRIMARY KEY ("SERVICE_ROUTINGS_ID") using index PUBLIC.SERVICE_ROUTINGS_PK ENABLE;



  ALTER TABLE "PUBLIC"."SERVICE_TYPES" ADD CONSTRAINT "SERVICE_TYPES_PK" PRIMARY KEY ("SERVICE_TYPE_ID") using index PUBLIC.SERVICE_TYPES_PK ENABLE;



  ALTER TABLE "PUBLIC"."TARGET_APPLICATIONS" ADD CONSTRAINT "TARGET_APPLICATIONS_PK" PRIMARY KEY ("TARGET_APPLICATION_ID") using index PUBLIC.TARGET_APPLICATIONS_PK ENABLE;


