spring:
  jms:
    servicebus:
      connection-string: ${CIVIL_SDT_SERVICEBUS_CONNECTION_STRING:Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      internal:
        targetAppQueue:
          MCOL: ${CIVIL_SDT_QUEUE}
