spring:
  jms:
    servicebus:
      connection-string: ${CIVIL_SDT_SERVICEBUS_CONNECTION_STRING:Endpoint=sb://hmc-servicebus-demo.servicebus.windows.net/;SharedAccessKeyName=Root;SharedAccessKey=xSKPYY74WsGHXIhSyj3Bk91fCp8TBLyAjAkn/GvGpOE=;EntityPath=civil_sdt_inbound}
      internal:
        targetAppQueue:
          MCOL: civil_sdt_inbound
