spring:
  jms:
    servicebus:
      connection-string: ${SDT_QUEUE_CONNECTION_STRING::Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      internal:
        queueConfig:
          MCOL: ${MCOL.Queue}
