
  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_CUSTOMERS" FOR "SDT_OWNER"."BULK_CUSTOMERS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_CUSTOMER_APPLICATIONS" FOR "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_CUST_APP_SEQ" FOR "SDT_OWNER"."BULK_CUST_APP_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_CUST_SEQ" FOR "SDT_OWNER"."BULK_CUST_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_SUBMISSIONS" FOR "SDT_OWNER"."BULK_SUBMISSIONS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."BULK_SUB_SEQ" FOR "SDT_OWNER"."BULK_SUB_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."ERROR_LOGS" FOR "SDT_OWNER"."ERROR_LOGS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."ERROR_MESSAGES" FOR "SDT_OWNER"."ERROR_MESSAGES";



  CREATE OR REPLACE SYNONYM "SDT_USER"."ERR_LOG_SEQ" FOR "SDT_OWNER"."ERR_LOG_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."ERR_MESG_SEQ" FOR "SDT_OWNER"."ERR_MESG_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."GLB_PAR_SEQ" FOR "SDT_OWNER"."GLB_PAR_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."GLOBAL_PARAMETERS" FOR "SDT_OWNER"."GLOBAL_PARAMETERS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."INDIVIDUAL_REQUESTS" FOR "SDT_OWNER"."INDIVIDUAL_REQUESTS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."IND_REQ_SEQ" FOR "SDT_OWNER"."IND_REQ_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."MESSAGE_LOGS" FOR "SDT_OWNER"."MESSAGE_LOGS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SDT_REF_SEQ" FOR "SDT_OWNER"."SDT_REF_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SERVICE_REQUESTS" FOR "SDT_OWNER"."SERVICE_REQUESTS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SERVICE_ROUTINGS" FOR "SDT_OWNER"."SERVICE_ROUTINGS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SERVICE_TYPES" FOR "SDT_OWNER"."SERVICE_TYPES";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SER_ROU_SEQ" FOR "SDT_OWNER"."SER_ROU_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SER_TYP_SEQ" FOR "SDT_OWNER"."SER_TYP_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."SRV_REQ_SEQ" FOR "SDT_OWNER"."SRV_REQ_SEQ";



  CREATE OR REPLACE SYNONYM "SDT_USER"."TARGET_APPLICATIONS" FOR "SDT_OWNER"."TARGET_APPLICATIONS";



  CREATE OR REPLACE SYNONYM "SDT_USER"."TAR_APP_SEQ" FOR "SDT_OWNER"."TAR_APP_SEQ";


