
  ALTER TABLE "PUBLIC"."BULK_SUBMISSIONS" ADD CONSTRAINT "BS_SBR_UNI" UNIQUE ("SDT_BULK_REFERENCE") ENABLE;



  ALTER TABLE "PUBLIC"."SERVICE_TYPES" ADD CONSTRAINT "RT_RTN_UNI" UNIQUE ("SERVICE_TYPE_NAME") ENABLE;



  ALTER TABLE "PUBLIC"."TARGET_APPLICATIONS" ADD CONSTRAINT "TA_TAN_UNI" UNIQUE ("TARGET_APPLICATION_NAME") ENABLE;


