spring:
  jms:
    servicebus:
      connection-string: ${SDT_QUEUE_CONNECTION_STRING:Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      enabled: false
    activemq:
      in-memory: true
      pool:
        enabled: false
      internal:
        queueConfig:
          MCOL: ${MCOL.Queue}
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:tc:postgresql:11:1:///civil_sdt_integ
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: ${SDT_DB_USERNAME:postgres}
    password: ${SDT_DB_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  flyway:
    enabled: false
sdt:
  tx-timeout:
    default:  1000
