spring:
  activemq:
    in-memory: true
    pool:
      enabled: false
  jms:
    servicebus:
      internal:
        targetAppQueue:
          MCOL: ${CIVIL_SDT_QUEUE}
      connection-string: ${CIVIL_SDT_SERVICEBUS_CONNECTION_STRING:Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      enabled: false

  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:tc:postgresql:11:///civil_sdt_integ?stringtype=unspecified
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: ${SDT_DB_USERNAME:postgres}
    password: ${SDT_DB_PASSWORD:test}
  jpa:
    database: postgresql
  flyway:
    enabled: false
sdt:
  tx-timeout:
    default:  1000
  service:
    config:
      concurrentConsumers: ${CONCURRENT_CONSUMERS:1}
      maxConcurrentConsumers: ${MAX_CONCURRENT_CONSUMERS:5}
      receiveTimeout: ${RECEIVE_TIMEOUT:30000}
      idleTaskExecutionLimit:  ${IDLE_TASK_EXECUTION_LIMIT:10}
      idleConsumerLimit:  ${IDLE_CONSUMER_LIMIT:5}
