spring:
  activemq:
    packages:
      trusted: uk.gov.moj.sdt.services.messaging
    in-memory: true
    pool:
      enabled: false
  jms:
    servicebus:
      internal:
        targetAppQueue:
          MCOL: ${CIVIL_SDT_QUEUE:McolQueue}
          MCOLS: ${CIVIL_SDT_QUEUE:McolsQueue}
          TEST1: ${CIVIL_SDT_QUEUE:Test1Queue}
      connection-string: ${CIVIL_SDT_SERVICEBUS_CONNECTION_STRING:Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      enabled: false

  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:tc:postgresql:15:///civil_sdt_integ?stringtype=unspecified
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: ${SDT_DB_USERNAME:postgres}
    password: ${SDT_DB_PASSWORD:test}
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    ignore-migration-patterns: true
sdt:
  tx-timeout:
    default:  1000
  service:
    config:
      concurrentConsumers: ${CONCURRENT_CONSUMERS:1}
      maxConcurrentConsumers: ${MAX_CONCURRENT_CONSUMERS:5}
      receiveTimeout: ${RECEIVE_TIMEOUT:30000}
      idleTaskExecutionLimit:  ${IDLE_TASK_EXECUTION_LIMIT:10}
      idleConsumerLimit:  ${IDLE_CONSUMER_LIMIT:5}
      queue_delay: ${QUEUE_DELAY:2000}
  purge:
    cron: ${PURGE_SCHEDULE_CRON:0 10 5 * * ?}
    commitInterval: ${PURGE_COMMIT_INTERVAL:1000}
  retry-send:
    cron: ${RETRY_SEND_CRON:0 0 * * * ?}
idam:
  s2s-auth:
    microservice: civil_sdt
    totp_secret: ${CIVIL_SDT_S2S_KEY:AAAAAAAAAAAAAAAA}
    url: ${IDAM_S2S_URL:http://localhost:4502}
  sdt:
    username: ${IDAM_SDT_USERNAME:master.sdt@gmail.com}
    password: ${IDAM_SDT_PASSWORD:Pa55word11}
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
