spring:
  activemq:
    packages:
      trust-all: true
    in-memory: true
    pool:
      enabled: false
  jms:
    servicebus:
      internal:
        queueConfig:
          MCOL: ${MCOL.Queue:Test1Queue}
          MCOLS: ${MCOLS.Queue:Test1Queue}
          TEST1: ${MCOL.Queue:Test1Queue}
      connection-string: ${SDT_QUEUE_CONNECTION_STRING:Endpoint=sb://destination1.servicebus.windows.net;SharedAccessKeyName=[KEYNAME];SharedAccessKey=[KEY]}
      enabled: false

  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:tc:postgresql:11:///civil_sdt_integ?stringtype=unspecified
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: ${SDT_DB_USERNAME:postgres}
    password: ${SDT_DB_PASSWORD:test}
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    ignore-migration-patterns: true
sdt:
  tx-timeout:
    default: test123
