CREATE USER sdt_owner
IDENTIFIED BY sdt_owner
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT,RESOURCE TO sdt_owner;

CREATE USER sdt_user
IDENTIFIED BY sdt_user
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT,CREATE SYNONYM to sdt_user;

CREATE USER sdt_batch_user
IDENTIFIED BY sdt_batch_user
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT to sdt_batch_user;
