TRUNCATE TABLE TARGET_APPLICATIONS CASCADE;

insert into TARGET_APPLICATIONS (TARGET_APPLICATION_ID, TARGET_APPLICATION_CODE, TARGET_APPLICATION_NAME, VERSION_NUMBER) VALUES (1,'MCOL','mcol live service', 1);

