INSERT INTO BULK_CUSTOMERS (BULK_CUSTOMER_ID, SDT_CUSTOMER_ID, VERSION_NUMBER, READY_FOR_ALTERNATE_SERVICE)
VALUES(10711, 12345678, 0, true);

INSERT INTO TARGET_APPLICATIONS (TARGET_APPLICATION_ID, TARGET_APPLICATION_CODE, TARGET_APPLICATION_NAME, VERSION_NUMBER)
VALUES(10713, 1104, 2, 0);

INSERT INTO BULK_CUSTOMER_APPLICATIONS (BULK_CUSTOMER_APPLICATIONS_ID, BULK_CUSTOMER_ID, TARGET_APPLICATION_ID, CUSTOMER_APPLICATION_ID, VERSION_NUMBER)
VALUES(1, 10711, 10713, '1', 0);

INSERT INTO BULK_SUBMISSIONS (BULK_SUBMISSION_ID, BULK_CUSTOMER_ID, TARGET_APPLICATION_ID, SDT_BULK_REFERENCE, CUSTOMER_REFERENCE, CREATED_DATE, NUMBER_OF_REQUESTS, BULK_SUBMISSION_STATUS, VERSION_NUMBER, BULK_PAYLOAD)
VALUES(14, 10711, 10713, 'MCOL-10012013010101-100099999', 'REF1', (current_date - INTERVAL '1 day'), 2, 'Validated', 0, '2');

INSERT INTO INDIVIDUAL_REQUESTS (INDIVIDUAL_REQUEST_ID, BULK_SUBMISSION_ID, CUSTOMER_REQUEST_REF, REQUEST_STATUS, SDT_BULK_REFERENCE, LINE_NUMBER, SDT_REQUEST_REFERENCE, CREATED_DATE, UPDATED_DATE, FORWARDING_ATTEMPTS,
      TARGET_APPLICATION_RESPONSE, REQUEST_TYPE, VERSION_NUMBER, DEAD_LETTER)
VALUES (1, 14, 'USER_REQUEST_ID_BF1', 'Accepted', 'MCOL-10012013010101-100099999', 1, 'MCOL-10012013010101-100099999-0001', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 1,
'<ns2:responseDetail><ind:mcolResponseDetail xmlns:ind="http://ws.sdt.moj.gov.uk/2013/sdt/BulkFeedbackResponseSchema" xmlns:mresp="http://ws.sdt.moj.gov.uk/2013/mcol/ResponseDetailSchema"><mresp:claimNumber>21346546</mresp:claimNumber><mresp:issueDate>2001-01-01</mresp:issueDate><mresp:serviceDate>2001-01-01</mresp:serviceDate><mresp:warrantNumber>12345678</mresp:warrantNumber><mresp:enforcingCourtCode>123</mresp:enforcingCourtCode>
<mresp:enforcingCourtName>Court Code</mresp:enforcingCourtName><mresp:fee>0</mresp:fee><mresp:judgmentWarrantStatus>tns additionalStatus</mresp:judgmentWarrantStatus></ind:mcolResponseDetail></ns2:responseDetail>', 'mcolClaim', 0, 'N');

INSERT INTO INDIVIDUAL_REQUESTS (INDIVIDUAL_REQUEST_ID, BULK_SUBMISSION_ID, CUSTOMER_REQUEST_REF, REQUEST_STATUS, SDT_BULK_REFERENCE, LINE_NUMBER, SDT_REQUEST_REFERENCE, CREATED_DATE, UPDATED_DATE, FORWARDING_ATTEMPTS,
      REQUEST_TYPE, VERSION_NUMBER, DEAD_LETTER, ERROR_LOG_ID)
VALUES (2, 14, 'USER_REQUEST_ID_BF2', 'Rejected', 'MCOL-10012013010101-100099999', 2, 'MCOL-10012013010101-100099999-0002', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 1, 'mcolClaim', 0, 'N', 1);

INSERT INTO ERROR_LOGS (ERROR_LOG_ID, INDIVIDUAL_REQUEST_ID, ERROR_CODE, CREATED_DATE, UPDATED_DATE, VERSION_NUMBER, ERROR_TEXT)
VALUES(1, 2, '1', (current_date - INTERVAL '1 day'), (current_date - INTERVAL '1 day'), 0, 'Error message.');
