ALTER TABLE INDIVIDUAL_REQUESTS ADD COLUMN ERROR_LOG_ID NUMERIC;
ALTER TABLE INDIVIDUAL_REQUESTS ADD COLUMN ISSUED_DATE TIMESTAMP(6);
ALTER TABLE INDIVIDUAL_REQUESTS ALTER DEAD_LETTER TYPE boolean
  USING CASE DEAD_LETTER WHEN 'Y' THEN true ELSE false END;

CREATE INDEX ir_error_logs_id ON individual_requests (error_log_id);
