SET ECHO ON

-------------------------------------------------------------
-- Drop each of the schemas used by SDT and all their contents
--------------------------------------------------------------
DROP SCHEMA IF EXISTS "SDT_USER" CASCADE;
DROP SCHEMA IF EXISTS "SDT_BATCH_USER" CASCADE;
DROP SCHEMA IF EXISTS "SDT_OWNER" CASCADE;

-------------------------------------------------------------
-- Drop each of the users used by SD
--------------------------------------------------------------
-- non schema owners first
DROP USER IF EXISTS SDT_USER;
DROP USER IF EXISTS SDT_BATCH_USER;
-- now schema owners
DROP USER IF EXISTS SDT_OWNER;

-------------------------------------------------------------
-- Create the schemas used by SDT and all their contents
--------------------------------------------------------------
CREATE SCHEMA "SDT_OWNER";
CREATE SCHEMA "SDT_USER";
CREATE SCHEMA "SDT_BATCH_USER";

------------------------------------------------
-- Create each of the schemas used by SDT
------------------------------------------------
CREATE USER SDT_OWNER;
GRANT POSTGRES TO SDT_OWNER;

CREATE USER SDT_USER;
GRANT POSTGRES TO SDT_USER;
CREATE USER SDT_BATCH_USER;
GRANT POSTGRES TO SDT_BATCH_USER;

------------------------------------------------
-- Create tables for SDT_OWNER
------------------------------------------------
  CREATE TABLE "SDT_OWNER"."BULK_CUSTOMERS"
   (BULK_CUSTOMER_ID NUMERIC NOT NULL,
	SDT_CUSTOMER_ID NUMERIC(8),
	VERSION_NUMBER NUMERIC DEFAULT 0
   ) ;

  CREATE TABLE "SDT_OWNER"."BULK_CUSTOMER_APPLICATIONS"
   (	"BULK_CUSTOMER_APPLICATIONS_ID" NUMERIC NOT NULL,
	"BULK_CUSTOMER_ID" NUMERIC,
	"TARGET_APPLICATION_ID" NUMERIC,
	"CUSTOMER_APPLICATION_ID" VARCHAR(32),
	"VERSION_NUMBER" NUMERIC DEFAULT 0
   ) ;

   CREATE TABLE "SDT_OWNER"."BULK_SUBMISSIONS"
   (	"BULK_SUBMISSION_ID" NUMERIC NOT NULL,
	"BULK_CUSTOMER_ID" NUMERIC,
	"TARGET_APPLICATION_ID" NUMERIC,
	"SERVICE_REQUEST_ID" NUMERIC,
	"SDT_BULK_REFERENCE" VARCHAR(29),
	"CUSTOMER_REFERENCE" VARCHAR(32),
	"CREATED_DATE" TIMESTAMP(6),
	"NUMBER_OF_REQUESTS" NUMERIC,
	"BULK_SUBMISSION_STATUS" VARCHAR(20),
	"COMPLETED_DATE" TIMESTAMP(6),
	"UPDATED_DATE" TIMESTAMP(6),
	"ERROR_CODE" VARCHAR(32),
	"ERROR_TEXT" VARCHAR(1000),
	"VERSION_NUMBER" NUMERIC DEFAULT 0,
	"BULK_PAYLOAD" BYTEA
   ) ;

  CREATE TABLE "SDT_OWNER"."ERROR_LOGS"
   (	"ERROR_LOG_ID" NUMERIC NOT NULL,
	"INDIVIDUAL_REQUEST_ID" NUMERIC,
	"ERROR_CODE" VARCHAR(32),
	"CREATED_DATE" TIMESTAMP(6),
	"UPDATED_DATE" TIMESTAMP(6),
	"VERSION_NUMBER" NUMERIC DEFAULT 0,
	"ERROR_TEXT" VARCHAR(1000)
   ) ;

  CREATE TABLE "SDT_OWNER"."ERROR_MESSAGES"
    (	"ERROR_MESSAGE_ID" NUMERIC,
 	"ERROR_CODE" VARCHAR(32),
 	"ERROR_TEXT" VARCHAR(1000),
 	"ERROR_DESCRIPTION" VARCHAR(2000),
 	"VERSION_NUMBER" NUMERIC DEFAULT 0
    ) ;

   CREATE TABLE "SDT_OWNER"."GLOBAL_PARAMETERS"
    (	"GLOBAL_PARAMETER_ID" NUMERIC,
 	"PARAMETER_NAME" VARCHAR(32),
 	"PARAMETER_VALUE" VARCHAR(32),
 	"PARAMETER_DESCRIPTION" VARCHAR(2000),
 	"VERSION_NUMBER" NUMERIC DEFAULT 0
    ) ;

  CREATE TABLE "SDT_OWNER"."INDIVIDUAL_REQUESTS"
   (	"INDIVIDUAL_REQUEST_ID" NUMERIC NOT NULL,
	"BULK_SUBMISSION_ID" NUMERIC,
	"CUSTOMER_REQUEST_REF" VARCHAR(32),
	"REQUEST_STATUS" VARCHAR(32),
	"SDT_BULK_REFERENCE" VARCHAR(29),
	"LINE_NUMBER" NUMERIC,
	"SDT_REQUEST_REFERENCE" VARCHAR(37),
	"CREATED_DATE" TIMESTAMP(6),
	"UPDATED_DATE" TIMESTAMP(6),
	"COMPLETED_DATE" TIMESTAMP(6),
	"FORWARDING_ATTEMPTS" NUMERIC,
	"DEAD_LETTER" CHAR(1),
	"INTERNAL_SYSTEM_ERROR" VARCHAR(4000),
	"REQUEST_TYPE" VARCHAR(50),
	"VERSION_NUMBER" NUMERIC DEFAULT 0,
	"INDIVIDUAL_PAYLOAD" BYTEA,
	"TARGET_APPLICATION_RESPONSE" BYTEA
   ) ;

  CREATE TABLE "SDT_OWNER"."SERVICE_REQUESTS"
   (	"SERVICE_REQUEST_ID" NUMERIC NOT NULL,
	"REQUEST_PAYLOAD" BYTEA,
	"REQUEST_TIMESTAMP" TIMESTAMP(6),
	"RESPONSE_PAYLOAD" BYTEA,
	"RESPONSE_TIMESTAMP" TIMESTAMP(6),
	"REQUEST_TYPE" VARCHAR(32),
	"SDT_CUSTOMER_ID" VARCHAR(32),
	"SDT_BULK_REFERENCE" VARCHAR(29),
	"SERVER_HOST_NAME" VARCHAR(255),
	"VERSION_NUMBER" NUMERIC DEFAULT 0
   ) ;

  CREATE TABLE "SDT_OWNER"."SERVICE_ROUTINGS"
   (	"SERVICE_ROUTINGS_ID" NUMERIC NOT NULL,
	"SERVICE_TYPE_ID" NUMERIC,
	"TARGET_APPLICATION_ID" NUMERIC,
	"WEB_SERVICE_ENDPOINT" VARCHAR(255),
	"VERSION_NUMBER" NUMERIC DEFAULT 0
   ) ;

  CREATE TABLE "SDT_OWNER"."SERVICE_TYPES"
   (	"SERVICE_TYPE_ID" NUMERIC NOT NULL,
	"SERVICE_TYPE_NAME" VARCHAR(50),
	"SERVICE_TYPE_STATUS" VARCHAR(1),
	"SERVICE_TYPE_DESCRIPTION" VARCHAR(2000),
	"VERSION_NUMBER" NUMERIC DEFAULT 0
   ) ;

  CREATE TABLE "SDT_OWNER"."TARGET_APPLICATIONS"
   (	"TARGET_APPLICATION_ID" NUMERIC NOT NULL,
	"TARGET_APPLICATION_CODE" VARCHAR(4),
	"TARGET_APPLICATION_NAME" VARCHAR(255),
	"VERSION_NUMBER" NUMERIC DEFAULT 0
   ) ;










SET ECHO OFF
