package uk.gov.moj.sdt.ws._2013.mcol.mcolinternalendpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-25T10:17:46.837+01:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/McolInternalEndpoint", name = "IMcolInternalEndpointPortType")
@XmlSeeAlso({uk.gov.moj.sdt.ws._2013.sdt.baseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.judgmentschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.defencefeedbackrequestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.responseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.warrantschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.requestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.defencefeedbackresponseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.claimschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.claimstatusupdateschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IMcolInternalEndpointPortType {

    @WebResult(name = "createResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "createResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.CreateResponseType createWarrant(
        @WebParam(partName = "createWarrantRequest", name = "createWarrantRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.CreateWarrantRequestType createWarrantRequest
    );

    @WebResult(name = "createResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "createResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.CreateResponseType updateClaim(
        @WebParam(partName = "updateClaimRequest", name = "updateClaimRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.UpdateClaimRequestType updateClaimRequest
    );

    @WebResult(name = "createResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "createResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.CreateResponseType createJudgment(
        @WebParam(partName = "createJudgmentRequest", name = "createJudgmentRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.CreateJudgmentRequestType createJudgmentRequest
    );

    @WebResult(name = "createResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "createResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.CreateResponseType createJudgmentWarrant(
        @WebParam(partName = "createJudgmentWarrantRequest", name = "createJudgmentWarrantRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.CreateJudgmentWarrantRequestType createJudgmentWarrantRequest
    );

    @WebResult(name = "defenceResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/DefenceFeedbackResponseSchema", partName = "parameters")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.defencefeedbackresponseschema.DefenceResponseType getDefenceDetails(
        @WebParam(partName = "parameters", name = "defenceRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/DefenceFeedbackRequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.defencefeedbackrequestschema.DefenceRequestType parameters
    );

    @WebResult(name = "createResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "createResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.CreateResponseType createClaim(
        @WebParam(partName = "createClaimRequest", name = "createClaimRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.CreateClaimRequestType createClaimRequest
    );
}
