package uk.gov.moj.sdt.ws._2013.mcol.mcolinternalendpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-29T12:33:49.285+01:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/McolInternalEndpoint", name = "IMcolInternalEndpointPortType")
@XmlSeeAlso({uk.gov.moj.sdt.ws._2013.sdt.baseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.submitqueryrequestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.judgmentschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.queryschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.responseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.warrantschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.requestschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.claimschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.submitqueryresponseschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.responsedetailschema.ObjectFactory.class, uk.gov.moj.sdt.ws._2013.mcol.claimstatusupdateschema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IMcolInternalEndpointPortType {

    @WebResult(name = "individualResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/ResponseSchema", partName = "individualResponse")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.responseschema.IndividualResponseType submitIndividual(
        @WebParam(partName = "individualRequest", name = "individualRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/RequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.requestschema.IndividualRequestType individualRequest
    );

    @WebResult(name = "submitQueryResponse", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/SubmitQueryResponseSchema", partName = "parameters")
    @WebMethod
    public uk.gov.moj.sdt.ws._2013.mcol.submitqueryresponseschema.SubmitQueryResponseType submitQuery(
        @WebParam(partName = "parameters", name = "submitQueryRequest", targetNamespace = "http://ws.sdt.moj.gov.uk/2013/mcol/SubmitQueryRequestSchema")
        uk.gov.moj.sdt.ws._2013.mcol.submitqueryrequestschema.SubmitQueryRequestType parameters
    );
}
