
  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."BULK_SUBMISSIONS" FOR "SDT_OWNER"."BULK_SUBMISSIONS";



  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."ERROR_LOGS" FOR "SDT_OWNER"."ERROR_LOGS";



  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."GLOBAL_PARAMETERS" FOR "SDT_OWNER"."GLOBAL_PARAMETERS";



  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."INDIVIDUAL_REQUESTS" FOR "SDT_OWNER"."INDIVIDUAL_REQUESTS";



  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."PURGE" FOR "SDT_OWNER"."PURGE";



  CREATE OR REPLACE SYNONYM "SDT_BATCH_USER"."SERVICE_REQUESTS" FOR "SDT_OWNER"."SERVICE_REQUESTS";


